name: Scraper Cron Workflow

on:
  schedule:
  - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2.3.4 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip requests
          python -m pip install --upgrade pip google_currency
          python -m pip install --upgrade pip datetime
          

      - name: Execute Python script # Run the script.py file to get the latest data
        run: |
          python ./utils/scraper/fx_scraper.py
          python ./utils/scraper/wise_scraper.py
        
      - name: Commit and push if the data has changed
        run: | 
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
